### ISSUE TITLE
Style suggestions

### ISSUE THREAD

**Issue by vrom911** [kowainik/hintman#102]
Make severity bold (or italic)?

**Comment by chshersh** [comment]
@vrom911 Good idea :+1: Let's make it bold. Also, let's rewrite the body of the review itself. We can use some fancy markdown there :slightly_smiling_face: Or probably add some useful information, like `Review by hintman v0.0.0.0, sha a12fj023jf02j` or I don't know is it useful or not...

**Comment by chshersh** [comment]
One more idea for the review body: we can tell, how many Hintman hints were found in this PR.

**Comment by chshersh** [comment]
_Review body_ of this issue is done! Now we only need to make severity bold :slightly_smiling_face:
