### ISSUE TITLE
[RFC] A lint for a lacking newline at the end of file

### ISSUE THREAD

**Issue by popzxc** [kowainik/hintman#154]
Since `github` highlights the files with the missing newline, it's a somewhat constant source of alike review comments:
![NoNewlineAtTheFileEnd](https://user-images.githubusercontent.com/12111581/71306564-fd7b5e80-23f2-11ea-8c34-50cd5de0ba9c.png)

It will be nice, if `hintman` will be able to detect those situations automatically, and provide a review comment.

I've already prototyped a solution, so if this will be considered a good idea, I'll be happy to create a corresponding PR :)

**Comment by chshersh** [comment]
Closed in #156
