### ISSUE TITLE
Instructions how to uninstall

### ISSUE THREAD

**Issue by andreasabel** [kowainik/hintman#166]
I could not find any instructions how to uninstall hint-man. Please add them to the README.

hint-man was (is?) running on my organization https://github.com/agda/ after someone installed it there, but weirdly, it was not showing to me under Settings/Installed Apps.  Thus, I could not delete it, even though I have the "Github App manager" capabilities.
After I installed it myself on this organization (was this a reinstallation?, it just went through without comment), it was showing up under "Installed Apps", and I could delete it.  (Though I am not sure whether it is actually deleted, since it was not showing before and is not showing now.)

**Comment by vrom911** [comment]
Hey @andreasabel !
Thanks for pointing to this. Sad to hear that you are experiencing some issues with that. From first glance, it sounds like some GitHub problems. This is purely GitHub mechanism of installing/uninstalling apps, which we do not entirely control. 
But I can definitely provide the instructions and update the README correspondingly. Please try this out:

1. Go to the Hintman App page: https://github.com/apps/hint-man
2. On this page you should see the "Configure" button: 
     <img width="1112" alt="Screenshot 2020-04-15 at 08 49 15" src="https://user-images.githubusercontent.com/8126674/79311972-1f46a700-7ef6-11ea-9372-fe79f5ec4588.png">
3. When you click on it, you will see the question "Where do you want to install hint-man?" and a number of organizations you have access to. If you already installed Hintman for the organization you should see the "Configure>" option:
    <img width="510" alt="Screenshot 2020-04-15 at 08 52 24" src="https://user-images.githubusercontent.com/8126674/79312810-56698800-7ef7-11ea-85eb-0ab694f91f9e.png">

4. When you click on that you will be brought to the your_org/Settings/Installed GitHub Apps/Hintman page. 
5. At the bottom of the page, there is an Uninstall option:
    <img width="766" alt="Screenshot 2020-04-15 at 08 54 36" src="https://user-images.githubusercontent.com/8126674/79312781-4baef300-7ef7-11ea-8376-aa8e0c4c8657.png">

Alternatively, you can:

1. Go directly to your organization Settings/Installed GitHub Apps. 
2. Choose Hintman from the list of your apps.
3. Click configure from there.
4. You will be brought to step 4 of the previous instructions.

Let me know if this works for you and I will add these instructions to the README file.
