### ISSUE TITLE
Proper aggregating structure for suggestions

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hintman#21]
So, since we now have multiple hints, it actually makes sense to think about aggregating structure. So the overal structure is the following:

1. Have the following top-level function
```haskell
suggest :: [(FilePath, Text)] -> [Suggestion]
```
It takes path to file and content of this file and performs `joinSuggestions . concatMap suggestSingle` where
2. The function `suggestSingle` will split incoming text over lines and then run all our suggestions either on every line or on the whole content
3. We might have multiple suggestions for single line so we need to aggregate suggestions. For example, if we have trailing line `   \n` we need to perform the only suggestion that removes this line, not two suggestions. So should `Suggestion` type be `Monoid` :thinking: Any ideas are appreciated!

cc @willbasky @sphaso @vrom911

**Comment by willbasky** [comment]
[#3](https://github.com/kowainik/hintman/pull/16)

**Comment by ChShersh** [comment]
@nixorn Is working on the `Config` type for checks. So we can add one more field to the `Suggestion` data type with something like `suggestionType :: SuggestionType` and then we can implement `Semigroup` instance for `Suggestion` that will handle joining of suggestions for us.

Not in PR #3, in separate PR, we're just discussing the architecture here :slightly_smiling_face:

**Comment by ChShersh** [comment]
@sphaso This also looks valid :+1:

**Comment by sphaso** [comment]
I'm implementing `suggestionType` in #14 , I have a doubt: `Suggest` currently does not have a line number, shouldn't it have one? how would we link a line number (input) with the suggestion otherwise? do you think it's better to have a `Line` type inside `Suggest` or just a `suggestLineNumber` field?

**Comment by ChShersh** [comment]
@sphaso I think you can rename `Suggest` data type to `LineChange` (or better name) and also introduce new data type:

```haskell
data Suggestion = Suggestion
    { suggestionLine :: Line
    , suggestionChange :: SuggestionChange
    }
```

**Comment by sphaso** [comment]
@ChShersh sorry, do you mean something like:
```Haskell
data Suggestion = Suggestion
    { suggestionLine : Line
    , suggestionFile : FilePath
    , suggestionChange : LineChange
    }

data LineChange = LineChange
    { lineChangeNew     :: Text
    , lineChangeComment :: Maybe Text  -- ^ Optional comment to the suggestion
    , lineChangeType :: ChangeType
    } deriving (Eq, Show)
```
?

**Comment by sphaso** [comment]
I've just pushed the types discussed above in #14
