### ISSUE TITLE
Don't fail when config file is not present

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hintman#44]
Currently `hintman` doesn't start when config file is not present. I think it's better to use default configuration in that case and print that it will be used.

**Comment by sphaso** [comment]
@ChShersh Just looking at the code, isn't this what's already happening?
https://github.com/kowainik/hintman/blob/cb84493693cea3bfe387e869dce885bd37608a15/src/Hintman/Config.hs#L45-L51

**Comment by vrom911** [comment]
I see that it catches only Tomland exceptions, and doesn't cover the case when the file is missing at all..
