### ISSUE TITLE
Write function to filter HLint hints according to diff

### ISSUE THREAD

**Issue by chshersh** [kowainik/hintman#55]
We can submit suggestions only to changed lines. We get this information from `diff-parse`. So we need to filter all hints according to diff.

**Comment by vrom911** [comment]
This is actually done during the work of `getTargetCommentPosition` function. Let me know if some other filters should be implemented.

**Comment by chshersh** [comment]
@vrom911 I double-checked the code. Looks like this issue is indeed done! Instead of keeping this one open, let's close it and create a new issue about further filtering only if we find something else.
