### ISSUE TITLE
Submit all hints when a PR is open

### ISSUE THREAD

**Issue by chshersh** [kowainik/hintman#56]
This is a final issue. Basically, wire up everything together. This is a tricky issue, we need to figure out how to use GitHub API to submit comments for corresponding lines....

**Comment by neongreen** [comment]
I think that GitHub also has an API for commenting on lines specifically if you do it via its "Check" mechanism:

![image](https://user-images.githubusercontent.com/1523306/63634247-5cef7a80-c65c-11e9-8e8f-b7ad0dd0521e.png)

(An example from https://github.com/domdere/haskell-lint-action.)

**Comment by chshersh** [comment]
@neongreen We've already figured out how to comment on specific lines. Github REST API provides an endpoint for submitting PR reviews. And GitHub `.diff` also contains enough information to provide valid arguments, so this is no longer a problem :ok_hand: 

Regarding `haskell-lint-action`: the documentation for this repo is minimal, it is not clear how it works and how it's implemented, so I can't extract value from this repo at the moment...
