### ISSUE TITLE
Implement config data type that contains all checks

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hintman#9]
We now have multiple checks. And it's probably a good idea to have a config for our tool anyways. So we can create `Config` data type where we can store all checks and allow users to have `.hintman.toml` in their repos to disable or enable checks.

Should go in `Hintman.Config` module.

**Comment by nixorn** [comment]
@ChShersh How should resulting config file looks like?

```yaml

checks = [
  "trailing-spaces",
  "trailing-newlines"
]
```

```haskell
data HintmanConfig = HintmanConfig {checks :: [Check]}
```

**Comment by vrom911** [comment]
@nixorn your understanding seems right! You can go ahead with this design 👍
